### PR TITLE
Update Zulip to v4.0.0

### PR DESCRIPTION
**Pull request by parndt**
https://github.com/zulip/zulip-desktop/releases/tag/v4.0.0

### CODE REVIEW

**Comment by parndt** [comment]
@ghisvail 	let me know if I've done anything incorrectly please :smile: 	thanks!

**Comment by ghisvail** [comment]
@parndt have you tried it locally ?

**Comment by parndt** [comment]
@ghisvail I did at the time, but I'm going to try it again just to see if anything's changed in a week, particularly as the test build 404s. I'll report back.

**Comment by parndt** [comment]
@ghisvail 	works fine for me.. reports being "Zulip Desktop v4.0.0"

image

I can confirm that the build from the stable branch reports "Zulip Desktop v3.0.0" so it is definitely using the different version. Seems to work fine for me. :tada: :+1:

**Comment by parndt** [comment]
Thanks!

**Pull request merged**
