### PR TITLE
Update Zulip Desktop to version 5.6.0

### PR DESCRIPTION
**Pull request by andersk**

### CODE REVIEW

**Comment by ghisvail** [comment]
Thanks @andersk

**Comment by andersk** [comment]
Is it possible I could get push access, as the upstream maintainer of Zulip Desktop, so that I can deploy to Flathub as part of our release checklist and our Flathub users don’t need to wait for updates?

**Comment by ghisvail** [comment]
Absolutely. Let me ask the FlatHub maintainers to give you commit rights.

@barthalion can you do it please, or should I ask somewhere else?

**Comment by barthalion** [comment]
Hey @andersk, invitation has been sent. Should we also invite someone more from Zulip team?

**Pull request merged**
