### PR TITLE
Update to 5.1.0

### PR DESCRIPTION
**Pull request by lazka**

### CODE REVIEW

**Comment by lazka** [comment]
Screenshot from 2020-04-30 07-13-06

**Comment by ghisvail** [comment]
Thanks!

**Comment by lazka** [comment]
Thanks!

The npm update wasn't very intuitive, should this be documented somewhere?

**Comment by ghisvail** [comment]
Indeed. I remembered someone in the community providing some useful bootstrapping scripts to fetch the upstream repo and `flatpak-builder-tools`, and then run the generator. I'll dig into it.

**Comment by lazka** [comment]
In my package I use a git submodule: https://github.com/flathub/io.github.quodlibet.QuodLibet

That and a README.md should be a good start imo

**Comment by ghisvail** [comment]
I don't think git submodules are an optimal solution here, tbh. All you are interested in is fetching the upstream repository at a certain commit or tag and updates the generated sources, which a workflow a script should be able to automate fully. With submodules, there is still some manual labor involved to fetch the right source code.

**Comment by lazka** [comment]
Agreed, making it reproducible is key, submodules are just one way to get there.

**Pull request merged**
