### PR TITLE
Add hack to make the tray icon work

### PR DESCRIPTION
**Pull request by lazka**
See #18

### CODE REVIEW

**Comment by lazka** [comment]
@TingPing could you maybe weigh in on whether this is acceptable or if you know any alternatives (this is an electron app built from source if that helps)

See https://github.com/flathub/org.zulip.Zulip/pull/20#issuecomment-625742977 for @ghisvail wishing more discussion on this.

**Comment by hstock** [comment]
I am on cinnamon. This build does not show an icon either. However, a very small empty space is created in the appindicators area which can be clicked. So the icon is "invisible and very small".

Seems to be related to this: https://github.com/electron/electron/issues/21445

**Comment by lazka** [comment]
Thanks. I've only tested under GNOME so far, where things look fine.

**Comment by lazka** [comment]
Looks like this is fixed, so closing. Thanks @ghisvail !

**Pull request closed without merging**
