### PR TITLE
Update to 5.2.0

### PR DESCRIPTION
**Pull request by lazka**

### CODE REVIEW

**Comment by lazka** [comment]
Screenshot from 2020-05-07 22-01-44

**Comment by lazka** [comment]
Screenshot from 2020-05-07 22-02-59

**Comment by ghisvail** [comment]
@lazka I have merged the update to v5.2.0 but left the tray icon hack or fix

 Tray icon breakage remains an open issue with people trying different things in different places, and I am reluctant to implement something which has not been properly validated by the Flathub community.

In the meantime, please don't hesitate to use an override with `--own-name=org.kde.*` as proposed in https://github.com/flathub/org.nextcloud.Nextcloud/issues/62. Should this fix be properly validated in the future, I'll welcome a PR for it :-)

**Comment by lazka** [comment]
fair enough, I've opened #22 for the tray icon

**Pull request merged**
